### ISSUE TITLE
Comments for Constructor not working

### ISSUE THREAD

**Issue by NCC1701M** [k--kato/vscode-docomment#49]
When you type /// above a constructor the auto completion is not working. On classes, Methods etc. it is working.

![csdoc](https://user-images.githubusercontent.com/7260053/27628586-c93a3100-5bef-11e7-993b-de7f1ed7572e.gif)

**Comment by k--kato** [comment]
regression: #47 @PJB3005

**Comment by PJB3005** [comment]
I definitely tested it, I'll get on it ASAP.

**Comment by PJB3005** [comment]
Ok this is weird. First of all it seems to be all methods, not just constructors. At least in my tests. Weirder however is that using enter *at all* seems broken, even before my changes. Which I'm suspecting is a cross platform issue because I developed the PR on a Mac but am not on a Windows PC and definitely able to reproduce everything. I'll fix this issue first and then see what's up with enter.
